/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdjuntementForm: typeof import('./src/components/inventory/AdjuntementForm.vue')['default']
    AdjustementForm: typeof import('./src/components/inventory/AdjustementForm.vue')['default']
    AdjustmentForm: typeof import('./src/components/inventory/AdjustmentForm.vue')['default']
    Appbar: typeof import('./src/components/Appbar.vue')['default']
    BacktoHome: typeof import('./src/components/common/BacktoHome.vue')['default']
    BaseFormDialog: typeof import('./src/components/forms/BaseFormDialog.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    CategoryProductForm: typeof import('./src/components/category/CategoryProductForm.vue')['default']
    CategoryProductList: typeof import('./src/components/category/CategoryProductList.vue')['default']
    ClientBasicInfo: typeof import('./src/components/forms/ClientBasicInfo.vue')['default']
    ClientContactInfo: typeof import('./src/components/forms/ClientContactInfo.vue')['default']
    ClientDelete: typeof import('./src/components/client/ClientDelete.vue')['default']
    ClientForm: typeof import('./src/components/client/ClientForm.vue')['default']
    ClientList: typeof import('./src/components/client/ClientList.vue')['default']
    DebtList: typeof import('./src/components/debt/DebtList.vue')['default']
    ExchaneRateForm: typeof import('./src/components/exchange/ExchangeRateForm.vue')['default']
    ExchangeRateForm: typeof import('./src/components/exchange/ExchangeRateForm.vue')['default']
    ExchangeRateList: typeof import('./src/components/exchange/ExchangeRateList.vue')['default']
    GuardarTasaBtn: typeof import('./src/components/GuardarTasaBtn.vue')['default']
    ImageUploader: typeof import('./src/components/forms/ImageUploader.vue')['default']
    InventoryList: typeof import('./src/components/inventory/InventoryList.vue')['default']
    InventoryMetrics: typeof import('./src/components/inventory/InventoryMetrics.vue')['default']
    LowStockAlert: typeof import('./src/components/inventory/LowStockAlert.vue')['default']
    OrderSummary: typeof import('./src/components/OrderSummary.vue')['default']
    PaymentModal: typeof import('./src/components/debt/PaymentModal.vue')['default']
    ProductBasicInfo: typeof import('./src/components/forms/ProductBasicInfo.vue')['default']
    ProductDetailModal: typeof import('./src/components/product/ProductDetailModal.vue')['default']
    ProductDetailRow: typeof import('./src/components/product/ProductDetailRow.vue')['default']
    ProductForm: typeof import('./src/components/product/ProductForm.vue')['default']
    ProductInventoryInfo: typeof import('./src/components/forms/ProductInventoryInfo.vue')['default']
    ProductList: typeof import('./src/components/product/ProductList.vue')['default']
    ProductPreparationInfo: typeof import('./src/components/forms/ProductPreparationInfo.vue')['default']
    ProductTable: typeof import('./src/components/product/ProductTable.vue')['default']
    PurchaseDetailDialog: typeof import('./src/components/purchase/PurchaseDetailDialog.vue')['default']
    PurchaseForm: typeof import('./src/components/purchase/PurchaseForm.vue')['default']
    PurchasesList: typeof import('./src/components/purchase/PurchasesList.vue')['default']
    ReloadButton: typeof import('./src/components/common/ReloadButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaleDetailModal: typeof import('./src/components/sale/SaleDetailModal.vue')['default']
    SaleForm: typeof import('./src/components/sale/SaleForm.vue')['default']
    SaleList: typeof import('./src/components/sale/SaleList.vue')['default']
    SearchFilter: typeof import('./src/components/common/SearchFilter.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SkeletonGrid: typeof import('./src/components/SkeletonGrid.vue')['default']
    SupplierForm: typeof import('./src/components/supplier/SupplierForm.vue')['default']
    SupplierList: typeof import('./src/components/supplier/SupplierList.vue')['default']
  }
}
