/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./src/components/Appbar.vue')['default']
    BacktoHome: typeof import('./src/components/common/BacktoHome.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    CardSkeleton: typeof import('./src/components/CardSkeleton.vue')['default']
    Cart: typeof import('./src/components/Cart.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    ClientDelete: typeof import('./src/components/client/ClientDelete.vue')['default']
    ClientForm: typeof import('./src/components/client/ClientForm.vue')['default']
    ClientList: typeof import('./src/components/client/ClientList.vue')['default']
    Example: typeof import('./src/components/example.vue')['default']
    OrderSummary: typeof import('./src/components/OrderSummary.vue')['default']
    ProductDelete: typeof import('./src/components/product/ProductDelete.vue')['default']
    ProductForm: typeof import('./src/components/product/ProductForm.vue')['default']
    ProductList: typeof import('./src/components/product/ProductList.vue')['default']
    Receipt: typeof import('./src/components/Receipt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/common/SearchFilter.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    SkeletonGrid: typeof import('./src/components/SkeletonGrid.vue')['default']
  }
}
